removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;
player forceAddUniform "U_B_CTRG_Soldier_F";
player addVest "V_PlateCarrier2_rgr";
player addBackpack "B_ViperLightHarness_oli_F";
player addHeadgear "H_HelmetB_TI_tna_F";
player addGoggles "G_Balaclava_oli";
player addWeapon "Rangefinder";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "ItemWatch";
player linkItem "TFAR_anprc152";
player linkItem "ItemGPS";
player setSpeaker "ace_novoice";
