removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;
player forceAddUniform "U_B_CTRG_Soldier_F";
player addItemToUniform "ACE_Flashlight_XL50";
player addItemToUniform "ACE_EarPlugs";
player addItemToUniform "ACE_Clacker";
player addItemToUniform "9Rnd_45ACP_Mag";
for "_i" from 1 to 2 do {player addItemToUniform "ACE_epinephrine";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_morphine";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_salineIV_500";};
player addVest "V_PlateCarrier2_rgr";
for "_i" from 1 to 10 do {player addItemToVest "UK3CB_BAF_9_30Rnd";};
for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
player addBackpack "B_ViperLightHarness_oli_F";
for "_i" from 1 to 4 do {player addItemToBackpack "DemoCharge_Remote_Mag";};
for "_i" from 1 to 5 do {player addItemToBackpack "UK3CB_BAF_9_30Rnd";};
for "_i" from 1 to 10 do {player addItemToBackpack "ACE_fieldDressing";};
player addHeadgear "H_HelmetB_TI_tna_F";
player addGoggles "G_Balaclava_oli";
player addWeapon "UK3CB_BAF_L92A1";
player addPrimaryWeaponItem "optic_ACO_grn_smg";
player addWeapon "hgun_ACPC2_F";
player addWeapon "Rangefinder";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "ItemWatch";
player linkItem "TFAR_anprc152";
player linkItem "ItemGPS";
player setSpeaker "ace_novoice";
